---
# BTRFS related stuff
- name: Install packages (pacman)
  pacman: name={{ item }} state=present
  with_items:
    - btrfs-progs
    - snapper
  when: ansible_pkg_mgr == "pacman"
  tags:
    - bootstrap
