---
- name: carthage playbook
  hosts: carthage
  vars:
    docker_opts : "--ip=127.0.0.1 --ip={{ carthage_ip }}"
  roles:
    - tersmitten.docker
    - nfs-client
  tasks:
    - name: Install git-annex
      apt: name:git-annex state=present
