---
- name: gohei playbook
  hosts: gohei
  roles:
    - tersmitten.docker
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ admin_user }}"
        groups: docker
        append: yes


