---
- name: gohei playbook
  hosts: gohei
  vars:
    - hostname: "gohei"
    - docker_opts: -H unix://var/run/docker.sock -H tcp://0.0.0.0:2375 --label storage=ssd --label typelaptop --label model=eeepc
  roles:
    - tersmitten.docker
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ admin_user }}"
        groups: docker
        append: yes


