---
- name: gohei playbook
  hosts: gohei
  vars:
    - hostname: "gohei"
    - docker_opts: -H tcp://0.0.0.0:2375 --label storage=ssd --label type=eeepc
  roles:
    - tersmitten.docker
#    - commons

