---
- name: hokkaido playbook
  hosts: hokkaido
  vars:
    - hostname: "utgard"
  roles:
    - commons
    - btrfs
    - arch-repos
    - configurations
#    - arch-laptop-common
    - arch-desktop-base
    - intel
#    - arch-desktop-awesome
#    - arch-desktop-dev-common
#    - arch-desktop-dev-java
#    - arch-docker
#    - ansible-host
  tasks:
    - name: "Update configurations"
      shell: cd $HOME && zsh -c "mr u"
