---
- name: hokkaido playbook
  hosts: hokkaido
  roles:
    - commons
    - common-users
    - arch-repos
    - configurations
    - arch-desktop-base
    - arch-desktop-slim
    - arch-laptop-common
    - intel
    - arch-desktop-i3
    - arch-desktop-dev-common
    - arch-desktop-dev-java
    - arch-docker
    - arch-virtualbox
    - ansible-host
  tasks:
    - name: "Thinkpad X220 Archlinux theme(s)"
      pacman: name=hokkaido-themes state=present
    - name: "Thinkpad X220 scaling down scaling_max_freq to 2.4GHz"
      copy: src=files/x220-scaling_max_freq.conf dest=/etc/tmpfiles.d/x220-scaling_max_freq.conf
    - name: "Thinkpad X220 default grub file"
      copy: src=files/x220-default-grub dest=/etc/default/grub
    - name: "Thinkpad X220 iwlwifi disable11n"
      copy: src=files/x220-iwlwifi-disable11n.conf dest=/etc/modprobe.d/iwlifi-disable11n.conf
