---
- name: hokkaido playbook
  hosts: hokkaido
  vars:
    - hostname: "hokkaido"
    - force_bepo: true
  roles:
    - commons
    - btrfs
    - arch-repos
    - configurations
    - arch-desktop-base
    - arch-laptop-common
    - intel
    - arch-desktop-awesome
    - arch-desktop-dev-common
    - arch-desktop-dev-java
    - arch-desktop-dev-javascript
    - arch-docker
    - ansible-host
  tasks:
    - name: "Thinkpad X220 Archlinux theme(s)"
      pacman: name=hokkaido-themes state=present
    - name: "Thinkpad X220 scaling down scaling_max_freq to 2.4GHz"
      copy: src=files/x220-scaling_max_freq.conf dest=/etc/tmpfiles.d/x220-scaling_max_freq.conf
    - name: "Thinkpad X220 default grub file"
      copy: src=files/x220-default-grub dest=/etc/default/grub
