---
- name: honshu playbook
  hosts: honshu
  roles:
    - commons
    - common-users
    - arch-repos
    - configurations
    - willshersystems.sshd
    - arch-desktop-base
    - arch-desktop-slim
    - arch-laptop-common
    - intel
    - arch-desktop-i3
    - arch-desktop-dev-common
    - arch-desktop-dev-java
    - arch-desktop-dev-go
    - arch-docker
    - arch-virtualbox
    - ansible-host
  tasks:
    - name: "Honshu Archlinux theme(s)"
      pacman: name=honshu-themes state=present
    - name: "Honshu default grub file"
      copy: src=files/honshu-default-grub dest=/etc/default/grub
    - name: "Add xrandr startup script (dual-screen)"
      copy: src=files/pre.xrandr.sh dest=/home/vincent/.xinitrc.d/pre.xrandr.sh mode=0755
    - name: "Add background script (dual-screen)"
      copy: src=files/post.honshu-background.sh dest=/home/vincent/.xinitrc.d/post.honshu-background.sh mode=0755
      
