---
- name: honshu playbook
  hosts: honshu
  vars:
    - hostname: "honshu"
    - force_bepo: false
    - sshd:
        Compression: true
        PermitRootLogin: false
        Match:
          - Condition: "Group user"
            X11Forwarding: yes
    - docker_opts: -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --label storage=disk --label type=laptop --label model=dell
  roles:
    - commons
    - common-users
    - btrfs
    - arch-repos
    - configurations
    - willshersystems.sshd
    - arch-desktop-base
    - arch-desktop-slim
    - arch-laptop-common
    - intel
    - arch-desktop-awesome
    - arch-desktop-dev-common
    - arch-desktop-dev-java
    - arch-desktop-dev-javascript
    - arch-desktop-go
    - arch-docker
    - ansible-host
    - adham.helal.msmtp
    - synergy
  tasks:
    - name: "Honshu Archlinux theme(s)"
      pacman: name=honshu-themes state=present
    - name: "Honshu default grub file"
      copy: src=files/honshu-default-grub dest=/etc/default/grub
    - name: "Add xrandr startup script (dual-screen)"
      copy: src=files/pre.xrandr.sh dest=/home/vincent/.xinitrc.d/pre.xrandr.sh mode=0755
    - name: "Add background script (dual-screen)"
      copy: src=files/post.honshu-background.sh dest=/home/vincent/.xinitrc.d/post.honshu-background.sh mode=0755
      
