---
- name: kerkouane playbook
  hosts: kerkouane
  vars:
    docker_opts : "{{ docker.default_opts }} -H tcp://{{ kerkouane_ip }}:2375 {{ docker.online_opts }} --label visibility=public"
  roles:
    - tersmitten.docker
    - nfs-client
  tasks:
    - name: Install git-annex
      apt: name=git-annex state=present
