---
- name: kyuhsu playbook
  hosts: kyushu
  vars:
    - hostname: "kyushu"
    - docker_opts: "{{ docker.default_opts }} {{ docker.local_opts }} --label storage=disk --label type=laptop --label model=thinkpad"
  roles:
    - tersmitten.docker
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ admin_user }}"
        groups: docker
        append: yes


