---
- name: kyuhsu playbook
  hosts: kyushu
  vars:
    - hostname: "kyushu"
    - docker_opts: -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --label storage=disk --label type=laptop --label model=thinkpad
  roles:
    - tersmitten.docker
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ admin_user }}"
        groups: docker
        append: yes


