---
- name: kyuhsu playbook
  hosts: kyushu
  vars:
    - hostname: "kyushu"
    - docker_opts: -H tcp://0.0.0.0:2375 --label storage=disk --label type=thinkpad$
  roles:
    - tersmitten.docker
#    - commons

