---
# Archlinux add pacman.d files instead of editing
- name: apply common configuration to all archlinux nodes
  hosts: utgard
  vars:
    - hostname: "utgard"
  roles:
    - commons
    - arch-repos
    - nvidia
    - configurations
    - arch-desktop-base
    - arch-desktop-awesome
  tasks:
    - name: "Update configurations"
      shell: mr u
      sudo: yes
      sudo_user: "{{ admin_user }}"

