---
# Archlinux add pacman.d files instead of editing
- name: apply common configuration to all archlinux nodes
  hosts: utgard
  roles:
    - commons
    - arch-repos
    - nvidia
    - arch-desktop

