---
# Languages
- name: Install python stuff
  pacman: name={{ item }} state=present
  with_items:
    - python2
    - python-pip
    - python2-pip
    - python-virtualenv
    - python-virtualenvwrapper
    - ipython

- name: Get python-config (vcsh)
  shell: vcsh clone git://github.com/vdemeester/python-config.git creates="/home/{{ admin_user }}/.config/vcsh/repo.d/python-config.git/config"
  sudo: yes
  sudo_user: "{{ admin_user }}"

- name: Install haskell stuff
  pacman: name={{ item }} state=present
  with_items:
    - ghc
    - cabal-install
    - cabal-dev

- name: Get haskell-config (vcsh)
  shell: vcsh clone git://github.com/vdemeester/haskell-config.git creates="/home/{{ admin_user }}/.config/vcsh/repo.d/haskell-config.git/config"
  sudo: yes
  sudo_user: "{{ admin_user }}"  
