---
- name: Install ntp (apt)
  pacman: name=ntp state=present
  when: ansible_pkg_mgr == "apt"

- name: Install vim (apt)
  pacman: name=vim state=present
  tags: 
    - vim
  when: ansible_pkg_mgr == "apt"

- name: Install tmux (apt)
  pacman: name=tmux state=present
  tags:
    - tmux
  when: ansible_pkg_mgr == "apt"

- name: Install htop (apt)
  pacman: name=htop state=present
  tags:
    - htop
  when: ansible_pkg_mgr == "apt"
