---
- name: Install ntp (apt)
  apt: name=ntp state=present
  when: ansible_pkg_mgr == "apt"

- name: Install minimals (apt)
  apt: name=vim,tmux,htop,tree,zsh state=present
  when: ansible_pkg_mgr == "apt"

- name: Install backups (apt)
  apt: name=obnam state=present
  when: ansible_pkg_mgr == "apt"
