---
- name: Install ntp (apt)
  pacman: name=ntp state=present
  when: ansible_pkg_mgr == "apt"

- name: Install minimals (apt)
  pacman: name=vim,tmux,htop,tree state=present
  when: ansible_pkg_mgr == "apt"

- name: Install backups (apt)
  pacman: name=obnam state=present
  when: ansible_pkg_mgr == "apt"
