---
- name: Install ntp (pacman)
  pacman: name=ntp state=present
  when: ansible_pkg_mgr == "pacman"

- name: Install minials (pacman)
  pacman: name=vim,tmux,htop,tree state=present
  when: ansible_pkg_mgr == "pacman"

- name: Install backups (pacman)
  pacman: name=obnam state=present
  when: ansible_pkg_mgr == "pacman"
