---
# This playbook contains common plays that will be run on all nodes.
- include: users.yml tags=users
- include: archlinux.yml tags=archlinux
- include: apt.yml tags=apt

# - name: Install emacs

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp
