---
# Docker on Archlinux
# TODO Add docker_opts to docker.service :P
- name: Install docker & stuff
  pacman: name={{ item }} state=present
  with_items:
    - docker
  tags:
    - minimal

- name: Add user to docker
  user: name={{ admin_user }} groups=docker append=yes

- name: Enable docker service
  shell: systemctl enable docker creates=/usr/lib/systemd/system/docker.socket
