---
galaxy_info:
  author: Matt Willsher
  description: OpenSSH SSH deamon configuration
  company: Willsher Systems
  license: LGPLv3
  min_ansible_version: 1.8
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: FreeBSD
    version:
    - 10.1
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - system
dependencies: []
