---
# Awesome-wm on archlinux
- name: Install ai3wm
  pacman: name={{ item }} state=present
  with_items:
    - i3-wm
    - i3lock
    - i3status
  tags:
    - minimal

- name: Get i3-config
  shell: vcsh clone git://github.com/vdemeester/i3-config.git creates="/home/{{ admin_user }}/.config/vcsh/repo.d/i3-config.git/config"
  sudo: yes
  sudo_user: "{{ admin_user }}"
