---
# Audios (pulseaudio)
- name: Install pulseaudio
  pacman: name={{ item }} state=present
  with_items:
    - pulseaudio
    - pulseaudio-alsa
    - paprefs
    - pavucontrol
    - ponymix
  tags:
    - minimal

- name: Install additionnals
  pacman: name={{ item }} state=present
  with_items:
    - pulseaudio-ctl
    - pasystray-git
# configuration
