---
# Archlinux repostiories
- name: Add custom repo group include line
  lineinfile: dest=/etc/pacman.conf regexp="^Include \= \/etc/pacman\.d/infinality" line="Include = /etc/pacman.d/infinality"

- name: Copy in custom repo config file
  copy: src=templates/infinality-bundle-pacman-conf dest=/etc/pacman.d/infinality

- name: Update pacman cache
  pacman: update_cache=yes

- name: Install fonts
  pacman: name={{ item }} state=present
  with_items:
    - fontconfig-infinality-ultimate
    - freetype2-infinality-ultimate
    - cairo-infinality-ultimate
    - ibfonts-meta-base
    - ibfonts-meta-extended
    - ibfonts-meta-extended-lt
    - ttf-symbola-ib

- name: Install main packages (xorg required)
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xorg-xinput
    - xorg-xev
    - xorg-xrdb
    - xorg-xset
    - xorg-xmessage
    - xdg-utils
    - xdg-user-dirs
    - xf86-input-evdev
    - sbr-keymaps
    - xterm
    - rxvt-unicode
    - scrot
    - feh
    - polkit
    - unclutter

- name: Add default keyboard configuration (fr)
  copy: src=10-keyboard.conf dest=/usr/share/X11/xorg.conf.d/10-keyboard.conf
  when: force_bepo == false

- name: Add bepo default keyboard configuration
  copy: src=10-keyboard-bepo.conf dest=/usr/share/X11/xorg.conf.d/10-keyboard.conf
  when: force_bepo == true

- name: Add Personal bepo keyboard configuration with typematrix
  copy: src=10-typematrix.conf dest=/usr/share/X11/xorg.conf.d/10-typematrix.conf

- include: configurations.yml tags=configuration
- include: packages.yml
- include: audios.yml tags=audio
- include: network.yml tags=network
  
# wmname
