---
# desktop additionnal packages
- name: Install utilities
  pacman: name={{ item }} state=present
  with_items:
    - git-annex-bin
    - keychain
    - profile-sync-daemon
    - profile-cleaner
    - udiskie
    - libnotify
    - p7zip

- name: Install qt stuff
  pacman: name={{ item }} state=present
  with_items:
    - qtcurve-qt4
    - qtcurve-qt5
    - qtcurve-gtk2
    - qtcurve-kde4
    - qtcurve-utils
    - qtcurve-style-numix
    - python-pyqt4
    - python-pyqt5

- name: Install web related packages
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - google-chrome

- name: Install chat related packages
  pacman: name={{ item }} state=present
  with_items:
    - gajim

- name: Install multimedia packages
  pacman: name={{ item }} state=present
  with_items:
    - beets
    - mpv
    - ffmpeg
    - mencoder
    - mpc
    - ncmpcpp

- name: Install archlinux stuff
  pacman: name={{ item }} state=present
  with_items:
    - burp
    - cower
    - asp-git
    - ruby-fpm
    - ruby-fpm-cookery
