---
# desktop additionnal packages
- name: Install utilities
  pacman: name={{ item }} state=present
  with_items:
    - keychain
    - udiskie
    - libnotify
    - p7zip
    - unrar
    - xclip
    - geeqie
    - gimp
  tags:
    - minimal

- name: Install additionnal utilities
  pacman: name={{ item }} state=present
  with_items:
    - git-annex-bin
    - profile-sync-daemon
    - profile-cleaner
    - obnam
    - obnam
    - s3cmd

- name: Language stuff (correction/dictionnaries)
  pacman: name={{ item }} state=present
  with_items:
    - aspell
    - aspell-fr
    - aspell-en
    - hunspell
    - hunspell-fr
    - hunspell-en
  tags:
    - minimal

    
- name: Install qt stuff
  pacman: name={{ item }} state=present
  with_items:
    - qtcurve-qt4
    - qtcurve-qt5
    - qtcurve-gtk2
    - qtcurve-kde4
    - qtcurve-utils
    - qtcurve-style-numix
    - python-pyqt4
    - python-pyqt5

- name: Install web related packages
  pacman: name={{ item }} state=present
  with_items:
    - firefox
  tags:
    - minimal

- name: Install additionnal web related packages
  pacman: name={{ item }} state=present
    - google-chrome

- name: Install communication related packages
  pacman: name={{ item }} state=present
  with_items:
    - gajim
  tags:
    - minimal

- name: Install additionnal communication related packages
  pacman: name={{ item }} state=present
  with_items:
    - offlineimap
    - mu-git
    - cacert-dot-org
    - msmtp
    

- name: Install multimedia packages
  pacman: name={{ item }} state=present
  with_items:
    - beets
    - mpv
    - ffmpeg
    - mencoder
    - mpc
    - ncmpcpp
    - abcde

- name: Install archlinux stuff
  pacman: name={{ item }} state=present
  with_items:
    - pkgbuild-introspection
  tags:
    - minimal

- name: Install additionnal archlinux stuff
  pacman: name={{ item }} state=present
  with_items:
    - cower
    - asp-git
    - ruby-fpm
    - ruby-fpm-cookery

- name: Install latex stuff
  pacman: name={{ item }} state=present
  with_items:
    - texlive-most
    - texlive-lang
