---
- name: Ensure NFS utilities are installed.
  yum: name=nfs-utils state=installed

# This isn't necessary until exports are configured in /etc/exports.
# - name: Ensure rpcbind and nfs are running.
#   service: "name={{ item }} state=started enabled=yes"
#   with_items:
#     - rpcbind
#     - nfs
