---
# Java stuff
- name: Remove deprecated stuff
  pacman: name={{ item }} state=absent
  with_items:
    - jdk7-compat
    - jdk8-oracle

# FIXME Add oraclejdk8-* instead of jdk8-oracle
- name: Install language
  pacman: name={{ item }} state=present
  with_items:
    - jdk7-openjdk
    - jdk8-openjdk
    - groovy

- name: Install build tools
  pacman: name={{ item }} state=present
  with_items:
    - intellij-idea-14-ultimate

- name: Get java-config (vcsh)
  shell: vcsh clone git://github.com/vdemeester/java-config.git creates="/home/{{ admin_user }}/.config/vcsh/repo.d/java-config.git/config"
  sudo: yes
  sudo_user: "{{ admin_user }}"  
