---
# Common laptop configurations
- name: "Install network-manager"
  pacman: name={{ item }} state=present
  with_items:
    - networkmanager
    - networkmanager-openvpn
    - network-manager-applet
