---
- name: Ensure NFS utilities are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - nfs-common
    - nfs-kernel-server

# This isn't necessary until exports are configured in /etc/exports.
# - name: Ensure NFS is running.
#   service: name=nfs-kernel-server state=started enabled=yes
